services:
  - type: web
    name: stream-nexus-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Will be set manually in Render dashboard
      - key: JWT_SECRET
        sync: false # Will be set manually in Render dashboard
    autoDeploy: true 